version: '3'

services:
  postgres:
    image: postgres:14.5
    container_name: postgres_14
    hostname: db
    ports:
      - 6543:5432
    environment:
      POSTGRES_DB: "messenger"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      # - ./server/db/db_tables:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
  homeserver_frontend:
    build: .
    container_name: homeserver_frontend
    volumes:
      - .:/app
    ports:
      - 81:81
    links:
      - postgres
    depends_on:
      postgres:
        condition: 
          service_healthy